//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Vaerktojer.Prompt.Strings {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Vaerktojer.Prompt.Strings.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string ConfirmForm_Answer_No {
            get {
                return ResourceManager.GetString("ConfirmForm_Answer_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string ConfirmForm_Answer_Yes {
            get {
                return ResourceManager.GetString("ConfirmForm_Answer_Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vaerktojer.Prompt requires an interactive environment..
        /// </summary>
        internal static string Message_NotSupportedEnvironment {
            get {
                return ResourceManager.GetString("Message_NotSupportedEnvironment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ({0} items, {1}/{2} pages).
        /// </summary>
        internal static string Message_Pagination {
            get {
                return ResourceManager.GetString("Message_Pagination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The prompt was canceled..
        /// </summary>
        internal static string Message_PromptCanceled {
            get {
                return ResourceManager.GetString("Message_PromptCanceled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hit &lt;space&gt; to select, &lt;ctrl+a&gt; to toggle all, &lt;ctrl+i&gt; to invert selection.
        /// </summary>
        internal static string MultiSelectForm_Message_Hint {
            get {
                return ResourceManager.GetString("MultiSelectForm_Message_Hint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value is invalid.
        /// </summary>
        internal static string Validation_Invalid {
            get {
                return ResourceManager.GetString("Validation_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A maximum input of {0} items is required.
        /// </summary>
        internal static string Validation_Maximum_InputRequired {
            get {
                return ResourceManager.GetString("Validation_Maximum_InputRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The maximum ({0}) is not valid when minimum is set to ({1}).
        /// </summary>
        internal static string Validation_Maximum_OutOfRange {
            get {
                return ResourceManager.GetString("Validation_Maximum_OutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A maximum selection of {0} items is required.
        /// </summary>
        internal static string Validation_Maximum_SelectionRequired {
            get {
                return ResourceManager.GetString("Validation_Maximum_SelectionRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value is too long.
        /// </summary>
        internal static string Validation_MaxLength {
            get {
                return ResourceManager.GetString("Validation_MaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A minimum input of {0} items is required.
        /// </summary>
        internal static string Validation_Minimum_InputRequired {
            get {
                return ResourceManager.GetString("Validation_Minimum_InputRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The minimum ({0}) is not valid.
        /// </summary>
        internal static string Validation_Minimum_OutOfRange {
            get {
                return ResourceManager.GetString("Validation_Minimum_OutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A minimum selection of {0} items is required.
        /// </summary>
        internal static string Validation_Minimum_SelectionRequired {
            get {
                return ResourceManager.GetString("Validation_Minimum_SelectionRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value is too short.
        /// </summary>
        internal static string Validation_MinLength {
            get {
                return ResourceManager.GetString("Validation_MinLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value is not match pattern.
        /// </summary>
        internal static string Validation_RegularExpression {
            get {
                return ResourceManager.GetString("Validation_RegularExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value is required.
        /// </summary>
        internal static string Validation_Required {
            get {
                return ResourceManager.GetString("Validation_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} is incompatible type with {1}.
        /// </summary>
        internal static string Validation_Type_Incompatible {
            get {
                return ResourceManager.GetString("Validation_Type_Incompatible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} type does not have a {1} member.
        /// </summary>
        internal static string Validation_Type_MemberNotFound {
            get {
                return ResourceManager.GetString("Validation_Type_MemberNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot specify a method with arguments.
        /// </summary>
        internal static string Validation_Type_NotParameterlessMethod {
            get {
                return ResourceManager.GetString("Validation_Type_NotParameterlessMethod", resourceCulture);
            }
        }
    }
}
